import { useEffect, useState } from "react";
import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useSelector } from "react-redux";
import Image from "next/image";
import { motion, wrap } from "framer-motion";
import NumberDisplay from "@/components/numberDisplay";
import Footer from "@/components/footer";
import API from "../utilities/api";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const loginUser = useSelector((state) => state.user.user);
  const [whyUsData, setWhyUsData] = useState({});

  useEffect(() => {
    const fetchData = async () => {
      try {
        const { data } = await API.get("/orders/bestSellers");

        // Spread the users array and use role names as keys
        const updatedWhyUsData = {
          ...data,
          users: data.users.reduce((acc, curr) => {
            acc[curr.role] = curr.num;
            return acc;
          }, {}),
        };
        console.log(updatedWhyUsData);
        setWhyUsData(updatedWhyUsData);
      } catch (error) {
        console.log(error);
      }
    };

    fetchData();
    console.log("useEffect");
  }, []);

  const bestSellersCakes = [
    {
      path: "cheeseCake.jpg",
      name: "cheese cake",
      flavour: "Creamy",
      price: "950 AMD",
    },
    {
      path: "chocolateCake.jpg",
      name: "chocolate cake",
      flavour: "Creamy",
      price: "750 AMD",
    },
    {
      path: "hazelnutCake.jpg",
      name: "hazelnut cake",
      flavour: "Creamy",
      price: "750 AMD",
    },
    {
      path: "cheeseCake2.jpg",
      name: "cheese cake",
      flavour: "Creamy",
      price: "950 AMD",
    },
  ];
  const Cakes = [
    {
      path: "pastries.webp",
      name: "Pastries",
    },
    {
      path: "create.webp",
      name: "Create",
    },
    {
      path: "celebration.webp",
      name: "Celebration",
    },
    {
      path: "create.webp",
      name: "Create",
    },
  ];
  return (
    <>
      <Head>
        <title>Glorious</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.home}>
          <div className={styles.homeDiv}>
            <div>
              <h1 className="text-4xl">
                Create greate memories with love and sweetness
              </h1>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer
                sed neque accumsan, gravida velit a, semper ipsum. Proin at
                metus luctus.
              </p>
            </div>
            <div
              style={{
                display: "flex",
              }}
            >
              <motion.button
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.99 }}
                style={{
                  backgroundColor: "pink",
                  color: "#a71b52",
                  fontSize: "80%",
                }}
              >
                ORDER NOW
              </motion.button>
              <motion.button
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.99 }}
                style={{
                  backgroundColor: "transparent",
                  color: "white",
                  border: "1px solid white",
                  fontSize: "80%",
                }}
              >
                LEARN MORE
              </motion.button>
            </div>
          </div>
          <div className={styles.homeDiv}>
            <motion.div
              initial={{ scale: 1 }}
              animate={{ scale: [1, 1.03, 1] }}
              transition={{
                duration: 4,
                repeat: Infinity,
                repeatType: "loop",
                ease: "easeInOut",
              }}
            >
              <Image
                priority
                src="/images/strawberryBiscuit.png"
                alt="Example Image"
                width={300}
                height={400}
                className={styles["image-3d"]}
              />
            </motion.div>
          </div>
        </div>
        <div
          className={`${styles.dFlexColumn} ${styles.whyUsNumber}`}
          style={{
            justifyContent: "space-around",
          }}
        >
          <h1>Why Us ?</h1>
          <div
            className={styles.dFlexRow}
            style={{
              width: "100%",
              justifyContent: "space-around",
            }}
          >
            <div className={styles.dFlexColumn}>
              <NumberDisplay
                targetNumber={whyUsData?.numProducts ?? 0}
                duration={3}
              />
              <p>more products</p>
            </div>
            <div className={styles["vertical-line"]}></div>
            <div className={styles.dFlexColumn}>
              <NumberDisplay
                targetNumber={whyUsData?.users?.CLIENT ?? 0}
                duration={3}
              />
              <p>customers</p>
            </div>
            <div className={styles["vertical-line"]}></div>
            <div className={styles.dFlexColumn}>
              <NumberDisplay
                targetNumber={whyUsData?.users?.COMPANY ?? 0}
                duration={3}
              />
              <p>company</p>
            </div>
            <div className={styles["vertical-line"]}></div>
            <div className={styles.dFlexColumn}>
              <NumberDisplay
                targetNumber={whyUsData?.numOrders ?? 0}
                duration={3}
              />
              <p>implemented orders</p>
            </div>
          </div>
        </div>
        <div
          className={`${styles.memorySection} ${styles.dFlexRow}`}
          style={{
            justifyContent: "space-around",
          }}
        >
          <motion.div
            initial={{ scale: 1 }}
            animate={{ scale: [1, 1.03, 1] }}
            transition={{
              duration: 4,
              repeat: Infinity,
              repeatType: "loop",
              ease: "easeInOut",
            }}
          >
            <Image
              priority
              src="/images/strawberryCake.png"
              alt="Example Image"
              width={250}
              height={250}
              className={styles["image-3d"]}
            />
          </motion.div>
          <div>
            <h1>Unforgettable Moments</h1>
            <p>
              An Opportunity to see loved ones around a table even without an
              occasion
            </p>
          </div>
        </div>
        <div
          className={`${styles.bestSellers} ${styles.dFlexRow}`}
          style={{
            justifyContent: "space-evenly",
            flexWrap: "wrap",
          }}
        >
          {bestSellersCakes?.map((cake, index) => (
            <motion.div
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.99 }}
              className={styles.cakeCard}
              key={index}
            >
              <Image
                priority
                src={`/images/${cake.path}`}
                alt="Example Image"
                width={300}
                height={400}
                className={styles["cakeCardImg"]}
              />
              <div
                style={{
                  paddingLeft: "20px",
                  display: "flex",
                  height: "30%",
                  flexDirection: "column",
                  justifyContent: "center",
                  color: "black",
                }}
              >
                <h4>{cake.name}</h4>
                <p>Flavour : {cake.flavour}</p>
                <h4>{cake.price}</h4>
              </div>
            </motion.div>
          ))}
        </div>
        <div className="flex justify-center items-center flex-wrap py-10">
          {whyUsData?.categories?.map((cake, index) => (
            <motion.div
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.99 }}
              key={index}
              style={{
                position: "relative",
                borderRadius: "7px",
                backgroundColor: "red",
              }}
              className={` h-52 md:h-60 m-2 ${
                index === 0 ? "w-4/12 md:w-3/12" : "w-2/12 md:w-1/12"
              }`}
            >
              <Image
                priority
                src={cake.url}
                alt="Example Image"
                width={300}
                height={400}
                className={styles["bestSellersSectionImg"]}
              />
              <div className={`${styles.bestSellersSectionName} text-sm`}>
                <p>{cake.nameEn}</p>
              </div>
            </motion.div>
          ))}
        </div>
        <Footer />
      </main>
    </>
  );
}
