import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useSelector } from "react-redux";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const loginUser = useSelector((state) => state.user.user);
  return (
    <>
      <Head>
        <title>Glorious</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Hello This is Glorious App</h1>
        <h5>Your Name is : {loginUser?.fullName}</h5>
        <h5>Your email is : {loginUser?.email}</h5>
        <h5>Your are : {loginUser?.role}</h5>
      </main>
    </>
  );
}
