import { useEffect } from "react";
import API from "@/utilities/api";
import { addLoginUser } from "@/redux/features/user";
import { useDispatch } from "react-redux";
import Head from "next/head";
const Layout = ({ children }) => {
  const dispatch = useDispatch();
  useEffect(() => {
    const fetchDate = async () => {
      try {
        const { data } = await API.get("/users/");
        if (data.user) {
          dispatch(addLoginUser(data.user));
        }
      } catch (error) {
        console.log(error);
      }
    };
    fetchDate();
  }, []);
  return (
    <div>
      <Head>
        <title>Glorious</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          paddingTop: "80px",
        }}
      >
        {children}
      </div>
    </div>
  );
};
export default Layout;
